// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hntkjjgjrxqgeqkrdnhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudGtqamdqcnhxZ2Vxa3Jkbmh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NTEzMzEsImV4cCI6MjA5NzUyNzMzMX0.LwncdYIYJofRLMjIsCgDerI0UtvO8VMUrOjjQgABY9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
