// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmamqbglpiukmkzmeoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtYW1xYmdscGl1a21rem1lb2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjE4NTUsImV4cCI6MjA3MDA5Nzg1NX0.lbf3oRExNVR7l1UJW0NN1IsWCkZSNqWRlH0-aJbhtzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});